### ISSUE TITLE
What is the password of zip file?

### ISSUE THREAD

**Issue by ltkhang** [vitoralbiero/afd_dataset_cleaned#1]
Dear Mr/Mrs,

I am doing a research that verify multiple pre-trained face recognition models on variety datasets, but I could not find pro-asian faces dataset until AFD. However the original one stored in Pan Baidu, which I do not have an account and could not create one either. Please share me the password of your cleaned version.

Sincerely,

**Comment by vitoralbiero** [comment]
Hello,

Send me an email on valbiero@nd.edu and I will share the password with you.

Vítor.

**Comment by Lannah-Chillie** [comment]
@ltkhang Hello, may i ask whether you got the password?
